baseURL = 'https://airplanecraft.github.io/website-airplanecraft-publish/'
languageCode = 'en-us'
title = 'Airplane Craft'
theme = 'hugo-clarity'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content'
    disabled = false
    languageCode = 'en-us'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Airplane Craft'
    weight = 1
    [languages.en.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
    [[languages.en.menu.main]]
      identifier = "Home"
	    title = "my blog"
      name = "Home"
      url = "/posts/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "tech"
      name = "Tech"
      url = "/categories/technology/"
      weight = 4
    [[languages.en.menu.main]]
      identifier = "airplanecraft"
      name = "AirPlaneCraft"
      url = "/categories/airplanecraft"
      weight = 5
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 6
    [[languages.en.menu.main]]
      identifier = "rss"
      name = "RSS"
      url = "/index.xml"
      weight = 8
  [languages.zh]
    contentDir = 'content'
    disabled = false
    languageCode = 'zh-cn'
    languageDirection = 'ltr'
    languageName = 'Chinese'
    title = '飞机模型'
    weight = 1
    [languages.zh.params]
      subtitle = 'Reference, Tutorials, and Explanations'
    [[languages.zh.menu.main]]
      identifier = "Home"
      name = "主页"
      url = "/posts"
      weight = 2
    [[languages.zh.menu.main]]
      identifier = "tech"
      name = "技术"
      url = "/categories/technology"
      weight = 4
    [[languages.zh.menu.main]]
      identifier = "airplanecraft"
      name = "航模"
      url = "/categories/airplanecraft"
      weight = 5
    [[languages.zh.menu.main]]
      identifier = "about"
      name = "关于我"
      url = "/about"
      weight = 6
    [[languages.zh.menu.main]]
      identifier = "rss"
      name = "RSS"
      url = "/index.xml"
      weight = 8



